Improved Command Feedback
CreativeConduit/WorldShaper pull request #11
Opened 2024-08-05 17:21 UTC by CodedStingray

2024-08-14 20:06 UTC, ZidArgs requested changes

2024-08-14 20:06 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/chat/WorldShaperMessages.java
>       * @param position The position that has been set
add missing params to doc

2024-08-14 20:06 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/chat/WorldShaperMessages.java
>       * @param index The index from which the position has been removed
add missing params to doc

2024-08-14 20:06 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/chat/WorldShaperMessages.java
> +    public static String actionPerformedMessage(int actionSize) {
add missing doc

2024-08-14 20:06 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/commands/area/operations/CommandCeiling.java
> +                    .t("A total of ").a(action.getActionSize()).t(" blocks have been modified").build()
missing period

2024-08-14 20:06 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/commands/clipboard/CommandMove.java
> +                    .t("Area contents stacked ").a(distance).t(" times ").a(direction.name().toLowerCase()).t(".").build()
stacked not moved?

2024-08-18 11:09 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/chat/WorldShaperMessages.java
>       * @param position The position that has been set
added

2024-08-18 11:09 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/chat/WorldShaperMessages.java
>       * @param index The index from which the position has been removed
added

2024-08-18 11:11 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/chat/WorldShaperMessages.java
> +    public static String actionPerformedMessage(int actionSize) {
added

2024-08-18 11:14 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/commands/area/operations/CommandCeiling.java
> +                    .t("A total of ").a(action.getActionSize()).t(" blocks have been modified").build()
This didn't even belong here and should've been the actionPerformedMessage from the WorldShaperMessages. Fixed it.

2024-08-18 11:15 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/commands/clipboard/CommandMove.java
> +                    .t("Area contents stacked ").a(distance).t(" times ").a(direction.name().toLowerCase()).t(".").build()
fixed

2024-08-18 15:31 UTC, ZidArgs approved these changes

2024-08-18 18:40 UTC, merged