Cclipboard System
CreativeConduit/WorldShaper pull request #4
Opened 2024-03-30 00:15 UTC by CodedStingray

2024-04-07 16:28 UTC, ZidArgs requested changes

2024-04-07 16:28 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/util/world/PositionedBlockData.java
> +}
add newline at the end

2024-04-07 16:28 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/util/world/PositionedBlockData.java
> +
remove newline in record

2024-04-07 16:34 UTC, ZidArgs commented on src/main/java/net/codedstingray/worldshaper/util/world/PositionedBlockData.java
> +public record PositionedBlockData(Vector3ii position, BlockData blockData) {
missing javadoc

2024-04-08 13:07 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/util/world/PositionedBlockData.java
> +
removed

2024-04-08 13:07 UTC, CodedStingray commented on src/main/java/net/codedstingray/worldshaper/util/world/PositionedBlockData.java
> +public record PositionedBlockData(Vector3ii position, BlockData blockData) {
added

2024-04-08 16:03 UTC, ZidArgs approved these changes

2024-04-08 16:24 UTC, merged